//! CounterRepository — abstract persistence for the Counter aggregate.
//!
//! This trait is the **only** way the counter application layer talks to storage.
//! Implementations may use libsql, Turso cloud, SurrealDB, or in-memory stubs.

use async_trait::async_trait;
use chrono::{DateTime, Utc};

use super::super::domain::{Counter, CounterId};

/// Errors that can occur during repository operations.
///
/// This is intentionally generic — the repository implementation maps its
/// specific errors (SQL, HTTP, etc.) into this type.
pub type RepositoryError = Box<dyn std::error::Error + Send + Sync>;

/// Specifies a counter mutation operation for atomic commit.
///
/// Used by `commit_mutation` to execute CAS mutation + outbox write
/// + idempotency cache in a single atomic statement.
#[derive(Debug, Clone)]
pub enum CounterOperation {
    Increment,
    Decrement,
    Reset,
}

/// Full specification for an atomic counter mutation commit.
#[derive(Debug, Clone)]
pub struct CounterMutation<'a> {
    pub counter_id: &'a CounterId,
    pub operation: CounterOperation,
    pub new_value: i64,
    pub new_version: i64,
    pub event_id: &'a str,
    pub event_type: &'a str,
    pub event_payload: &'a str,
    pub source_service: &'a str,
    pub correlation_id: Option<&'a str>,
}

/// Result of an atomic counter mutation commit.
pub enum CommitOutcome {
    /// Mutation succeeded.
    Committed { new_value: i64, new_version: i64 },
    /// CAS conflict: the counter was modified by another writer.
    CasConflict,
}

/// Abstract repository for Counter persistence with CAS support.
///
/// ## Responsibilities
/// - Store and retrieve Counter aggregates by CounterId
/// - Execute atomic increment/decrement/reset with CAS version check
/// - Write entries to the unified event_outbox
/// - Never leak business logic (no "default tenant" concepts here)
#[async_trait]
pub trait CounterRepository: Send + Sync {
    /// Load a counter by its ID. Returns None if not found.
    async fn load(&self, id: &CounterId) -> Result<Option<Counter>, RepositoryError>;

    /// Atomically increment a counter with CAS. Creates it if it doesn't exist.
    /// Returns (new_value, new_version) after increment.
    async fn increment(
        &self,
        id: &CounterId,
        expected_version: i64,
        now: DateTime<Utc>,
    ) -> Result<(i64, i64), RepositoryError>;

    /// Atomically decrement a counter with CAS.
    async fn decrement(
        &self,
        id: &CounterId,
        expected_version: i64,
        now: DateTime<Utc>,
    ) -> Result<(i64, i64), RepositoryError>;

    /// Reset a counter to zero with CAS.
    async fn reset(
        &self,
        id: &CounterId,
        expected_version: i64,
        now: DateTime<Utc>,
    ) -> Result<i64, RepositoryError>;

    /// Upsert a counter (used by application layer on first access).
    async fn upsert(&self, counter: &Counter) -> Result<(), RepositoryError>;

    /// Write an entry to the unified event_outbox.
    ///
    /// `event_id` is a UUID v7 generated by the application layer.
    async fn write_outbox(
        &self,
        event_id: &str,
        event_type: &str,
        payload: &str,
        source_service: &str,
        correlation_id: Option<&str>,
    ) -> Result<(), RepositoryError>;

    /// Check if an idempotency key was already processed.
    /// Returns Some((value, version)) if the key exists, None otherwise.
    async fn check_idempotency(&self, key: &str) -> Result<Option<(i64, i64)>, RepositoryError>;

    /// Cache an idempotency result for future deduplication.
    async fn cache_idempotency(
        &self,
        key: &str,
        value: i64,
        version: i64,
    ) -> Result<(), RepositoryError>;

    /// Atomically commit a counter mutation with CAS + outbox write + idempotency cache.
    ///
    /// Executes CAS counter update + event_outbox write in a single BEGIN/COMMIT
    /// transaction via `execute_batch`. If either the CAS mutation or outbox write
    /// fails, the entire transaction rolls back — no orphaned events, no phantom
    /// counter mutations.
    ///
    /// Idempotency cache write runs outside the transaction (best-effort). If it
    /// fails, the next retry with the same key will hit a CAS conflict (counter
    /// version already incremented), so the result remains correct — just the
    /// cache entry is missing and the next idempotent request will do a DB round-trip.
    ///
    /// Returns `CommitOutcome::CasConflict` when the expected_version doesn't match.
    async fn commit_mutation(
        &self,
        mutation: &CounterMutation<'_>,
        idempotency_key: Option<&str>,
    ) -> Result<CommitOutcome, RepositoryError>;
}
