name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Lint, Check, Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: moonrepo/setup-moon@v2

      - name: Run CI
        run: moon ci
